# Generated by Django 3.2.4 on 2022-05-02 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='paitAt',
            new_name='paidAt',
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='/static/images/placeholder.png', null=True, upload_to=''),
        ),
    ]
